// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: hyperlane/warp/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_troykessler_hyperlane_cosmos_util "github.com/troykessler/hyperlane-cosmos/util"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryTokensRequest ...
type QueryTokensRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTokensRequest) Reset()         { *m = QueryTokensRequest{} }
func (m *QueryTokensRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTokensRequest) ProtoMessage()    {}
func (*QueryTokensRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3514340e89a94dcf, []int{0}
}
func (m *QueryTokensRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokensRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokensRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokensRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokensRequest.Merge(m, src)
}
func (m *QueryTokensRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokensRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokensRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokensRequest proto.InternalMessageInfo

func (m *QueryTokensRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryTokensResponse ...
type QueryTokensResponse struct {
	// params defines the parameters of the module.
	Tokens []WrappedHypToken `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryTokensResponse) Reset()         { *m = QueryTokensResponse{} }
func (m *QueryTokensResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTokensResponse) ProtoMessage()    {}
func (*QueryTokensResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3514340e89a94dcf, []int{1}
}
func (m *QueryTokensResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokensResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokensResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokensResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokensResponse.Merge(m, src)
}
func (m *QueryTokensResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokensResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokensResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokensResponse proto.InternalMessageInfo

func (m *QueryTokensResponse) GetTokens() []WrappedHypToken {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func (m *QueryTokensResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryTokenRequest ...
type QueryTokenRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryTokenRequest) Reset()         { *m = QueryTokenRequest{} }
func (m *QueryTokenRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTokenRequest) ProtoMessage()    {}
func (*QueryTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3514340e89a94dcf, []int{2}
}
func (m *QueryTokenRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokenRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokenRequest.Merge(m, src)
}
func (m *QueryTokenRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokenRequest proto.InternalMessageInfo

func (m *QueryTokenRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// QueryTokenResponse ...
type QueryTokenResponse struct {
	Token *WrappedHypToken `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (m *QueryTokenResponse) Reset()         { *m = QueryTokenResponse{} }
func (m *QueryTokenResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTokenResponse) ProtoMessage()    {}
func (*QueryTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3514340e89a94dcf, []int{3}
}
func (m *QueryTokenResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTokenResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTokenResponse.Merge(m, src)
}
func (m *QueryTokenResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTokenResponse proto.InternalMessageInfo

func (m *QueryTokenResponse) GetToken() *WrappedHypToken {
	if m != nil {
		return m.Token
	}
	return nil
}

// / HypToken
type WrappedHypToken struct {
	Id            string                                                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner         string                                                   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	TokenType     HypTokenType                                             `protobuf:"varint,3,opt,name=token_type,json=tokenType,proto3,enum=hyperlane.warp.v1.HypTokenType" json:"token_type,omitempty"`
	OriginMailbox string                                                   `protobuf:"bytes,4,opt,name=origin_mailbox,json=originMailbox,proto3" json:"origin_mailbox,omitempty"`
	OriginDenom   string                                                   `protobuf:"bytes,5,opt,name=origin_denom,json=originDenom,proto3" json:"origin_denom,omitempty"`
	IsmId         *github_com_troykessler_hyperlane_cosmos_util.HexAddress `protobuf:"bytes,7,opt,name=ism_id,json=ismId,proto3,customtype=github.com/troykessler/hyperlane-cosmos/util.HexAddress" json:"ism_id,omitempty"`
}

func (m *WrappedHypToken) Reset()         { *m = WrappedHypToken{} }
func (m *WrappedHypToken) String() string { return proto.CompactTextString(m) }
func (*WrappedHypToken) ProtoMessage()    {}
func (*WrappedHypToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_3514340e89a94dcf, []int{4}
}
func (m *WrappedHypToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WrappedHypToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WrappedHypToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WrappedHypToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrappedHypToken.Merge(m, src)
}
func (m *WrappedHypToken) XXX_Size() int {
	return m.Size()
}
func (m *WrappedHypToken) XXX_DiscardUnknown() {
	xxx_messageInfo_WrappedHypToken.DiscardUnknown(m)
}

var xxx_messageInfo_WrappedHypToken proto.InternalMessageInfo

func (m *WrappedHypToken) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *WrappedHypToken) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *WrappedHypToken) GetTokenType() HypTokenType {
	if m != nil {
		return m.TokenType
	}
	return HYP_TOKEN_TYPE_UNSPECIFIED
}

func (m *WrappedHypToken) GetOriginMailbox() string {
	if m != nil {
		return m.OriginMailbox
	}
	return ""
}

func (m *WrappedHypToken) GetOriginDenom() string {
	if m != nil {
		return m.OriginDenom
	}
	return ""
}

// QueryBridgedSupplyRequest ...
type QueryBridgedSupplyRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryBridgedSupplyRequest) Reset()         { *m = QueryBridgedSupplyRequest{} }
func (m *QueryBridgedSupplyRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBridgedSupplyRequest) ProtoMessage()    {}
func (*QueryBridgedSupplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3514340e89a94dcf, []int{5}
}
func (m *QueryBridgedSupplyRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBridgedSupplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBridgedSupplyRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBridgedSupplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBridgedSupplyRequest.Merge(m, src)
}
func (m *QueryBridgedSupplyRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBridgedSupplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBridgedSupplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBridgedSupplyRequest proto.InternalMessageInfo

func (m *QueryBridgedSupplyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// QueryBridgedSupplyResponse ...
type QueryBridgedSupplyResponse struct {
	BridgedSupply types.Coin `protobuf:"bytes,1,opt,name=bridged_supply,json=bridgedSupply,proto3" json:"bridged_supply"`
}

func (m *QueryBridgedSupplyResponse) Reset()         { *m = QueryBridgedSupplyResponse{} }
func (m *QueryBridgedSupplyResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBridgedSupplyResponse) ProtoMessage()    {}
func (*QueryBridgedSupplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3514340e89a94dcf, []int{6}
}
func (m *QueryBridgedSupplyResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBridgedSupplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBridgedSupplyResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBridgedSupplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBridgedSupplyResponse.Merge(m, src)
}
func (m *QueryBridgedSupplyResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBridgedSupplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBridgedSupplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBridgedSupplyResponse proto.InternalMessageInfo

func (m *QueryBridgedSupplyResponse) GetBridgedSupply() types.Coin {
	if m != nil {
		return m.BridgedSupply
	}
	return types.Coin{}
}

// QueryRemoteRoutersRequest ...
type QueryRemoteRoutersRequest struct {
	Id         string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRemoteRoutersRequest) Reset()         { *m = QueryRemoteRoutersRequest{} }
func (m *QueryRemoteRoutersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRemoteRoutersRequest) ProtoMessage()    {}
func (*QueryRemoteRoutersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3514340e89a94dcf, []int{7}
}
func (m *QueryRemoteRoutersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRemoteRoutersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRemoteRoutersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRemoteRoutersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRemoteRoutersRequest.Merge(m, src)
}
func (m *QueryRemoteRoutersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRemoteRoutersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRemoteRoutersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRemoteRoutersRequest proto.InternalMessageInfo

func (m *QueryRemoteRoutersRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryRemoteRoutersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryRemoteRoutersResponse ...
type QueryRemoteRoutersResponse struct {
	// Remote Routers ...
	RemoteRouters []*RemoteRouter `protobuf:"bytes,1,rep,name=remote_routers,json=remoteRouters,proto3" json:"remote_routers,omitempty"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryRemoteRoutersResponse) Reset()         { *m = QueryRemoteRoutersResponse{} }
func (m *QueryRemoteRoutersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRemoteRoutersResponse) ProtoMessage()    {}
func (*QueryRemoteRoutersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3514340e89a94dcf, []int{8}
}
func (m *QueryRemoteRoutersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRemoteRoutersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRemoteRoutersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRemoteRoutersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRemoteRoutersResponse.Merge(m, src)
}
func (m *QueryRemoteRoutersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRemoteRoutersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRemoteRoutersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRemoteRoutersResponse proto.InternalMessageInfo

func (m *QueryRemoteRoutersResponse) GetRemoteRouters() []*RemoteRouter {
	if m != nil {
		return m.RemoteRouters
	}
	return nil
}

func (m *QueryRemoteRoutersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryQuoteRemoteTransferRequest ...
type QueryQuoteRemoteTransferRequest struct {
	Id                string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DestinationDomain string `protobuf:"bytes,2,opt,name=destination_domain,json=destinationDomain,proto3" json:"destination_domain,omitempty"`
}

func (m *QueryQuoteRemoteTransferRequest) Reset()         { *m = QueryQuoteRemoteTransferRequest{} }
func (m *QueryQuoteRemoteTransferRequest) String() string { return proto.CompactTextString(m) }
func (*QueryQuoteRemoteTransferRequest) ProtoMessage()    {}
func (*QueryQuoteRemoteTransferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3514340e89a94dcf, []int{9}
}
func (m *QueryQuoteRemoteTransferRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryQuoteRemoteTransferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryQuoteRemoteTransferRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryQuoteRemoteTransferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryQuoteRemoteTransferRequest.Merge(m, src)
}
func (m *QueryQuoteRemoteTransferRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryQuoteRemoteTransferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryQuoteRemoteTransferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryQuoteRemoteTransferRequest proto.InternalMessageInfo

func (m *QueryQuoteRemoteTransferRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryQuoteRemoteTransferRequest) GetDestinationDomain() string {
	if m != nil {
		return m.DestinationDomain
	}
	return ""
}

// QueryQuoteRemoteTransferResponse ...
type QueryQuoteRemoteTransferResponse struct {
	GasPayment github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=gas_payment,json=gasPayment,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"gas_payment"`
}

func (m *QueryQuoteRemoteTransferResponse) Reset()         { *m = QueryQuoteRemoteTransferResponse{} }
func (m *QueryQuoteRemoteTransferResponse) String() string { return proto.CompactTextString(m) }
func (*QueryQuoteRemoteTransferResponse) ProtoMessage()    {}
func (*QueryQuoteRemoteTransferResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3514340e89a94dcf, []int{10}
}
func (m *QueryQuoteRemoteTransferResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryQuoteRemoteTransferResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryQuoteRemoteTransferResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryQuoteRemoteTransferResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryQuoteRemoteTransferResponse.Merge(m, src)
}
func (m *QueryQuoteRemoteTransferResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryQuoteRemoteTransferResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryQuoteRemoteTransferResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryQuoteRemoteTransferResponse proto.InternalMessageInfo

func (m *QueryQuoteRemoteTransferResponse) GetGasPayment() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.GasPayment
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryTokensRequest)(nil), "hyperlane.warp.v1.QueryTokensRequest")
	proto.RegisterType((*QueryTokensResponse)(nil), "hyperlane.warp.v1.QueryTokensResponse")
	proto.RegisterType((*QueryTokenRequest)(nil), "hyperlane.warp.v1.QueryTokenRequest")
	proto.RegisterType((*QueryTokenResponse)(nil), "hyperlane.warp.v1.QueryTokenResponse")
	proto.RegisterType((*WrappedHypToken)(nil), "hyperlane.warp.v1.WrappedHypToken")
	proto.RegisterType((*QueryBridgedSupplyRequest)(nil), "hyperlane.warp.v1.QueryBridgedSupplyRequest")
	proto.RegisterType((*QueryBridgedSupplyResponse)(nil), "hyperlane.warp.v1.QueryBridgedSupplyResponse")
	proto.RegisterType((*QueryRemoteRoutersRequest)(nil), "hyperlane.warp.v1.QueryRemoteRoutersRequest")
	proto.RegisterType((*QueryRemoteRoutersResponse)(nil), "hyperlane.warp.v1.QueryRemoteRoutersResponse")
	proto.RegisterType((*QueryQuoteRemoteTransferRequest)(nil), "hyperlane.warp.v1.QueryQuoteRemoteTransferRequest")
	proto.RegisterType((*QueryQuoteRemoteTransferResponse)(nil), "hyperlane.warp.v1.QueryQuoteRemoteTransferResponse")
}

func init() { proto.RegisterFile("hyperlane/warp/v1/query.proto", fileDescriptor_3514340e89a94dcf) }

var fileDescriptor_3514340e89a94dcf = []byte{
	// 928 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0xae, 0xb3, 0x24, 0x28, 0x53, 0x1a, 0xd4, 0xa1, 0x42, 0x69, 0x58, 0x92, 0xae, 0xa1, 0x4b,
	0x54, 0x88, 0x4d, 0xb3, 0x20, 0x38, 0x81, 0x28, 0xa5, 0x2c, 0x02, 0x56, 0xbb, 0xde, 0x0a, 0x24,
	0x84, 0x64, 0x26, 0xf5, 0xe0, 0x1d, 0x35, 0xf6, 0xb8, 0x33, 0xe3, 0xb6, 0xd6, 0x6a, 0x2f, 0x9c,
	0x38, 0x22, 0x21, 0xae, 0xdc, 0x90, 0x10, 0x12, 0x12, 0x12, 0xfc, 0x11, 0x3d, 0x70, 0x58, 0xc1,
	0x05, 0x71, 0x28, 0xa8, 0x45, 0xe2, 0xdf, 0x40, 0x9e, 0x19, 0xb7, 0x76, 0x62, 0xb7, 0x01, 0x71,
	0x69, 0xe3, 0xf7, 0xeb, 0xfb, 0xde, 0x9b, 0xf7, 0x8d, 0x0d, 0x9e, 0xbe, 0x97, 0x44, 0x98, 0x8d,
	0x51, 0x88, 0xed, 0x03, 0xc4, 0x22, 0x7b, 0x7f, 0xdd, 0xde, 0x8b, 0x31, 0x4b, 0xac, 0x88, 0x51,
	0x41, 0xe1, 0xe2, 0x99, 0xdb, 0x4a, 0xdd, 0xd6, 0xfe, 0x7a, 0x67, 0x6d, 0x87, 0xf2, 0x80, 0x72,
	0x7b, 0x84, 0x38, 0x56, 0xb1, 0xf6, 0xfe, 0xfa, 0x08, 0x0b, 0xb4, 0x6e, 0x47, 0xc8, 0x27, 0x21,
	0x12, 0x84, 0x86, 0x2a, 0xbd, 0xd3, 0xcd, 0xc7, 0x66, 0x51, 0x3b, 0x94, 0x64, 0xfe, 0x12, 0x74,
	0x91, 0x44, 0x98, 0x6b, 0xf7, 0x55, 0x9f, 0x52, 0x7f, 0x8c, 0x6d, 0x14, 0x11, 0x1b, 0x85, 0x21,
	0x15, 0xb2, 0x76, 0xe6, 0x5d, 0x56, 0xc5, 0x5d, 0xf9, 0x64, 0xab, 0x07, 0xed, 0x5a, 0xf2, 0xa9,
	0x4f, 0x95, 0x3d, 0xfd, 0xa5, 0xad, 0x8b, 0x28, 0x20, 0x21, 0xb5, 0xe5, 0x5f, 0x65, 0x32, 0x3f,
	0x06, 0xf0, 0x4e, 0xda, 0xc2, 0x36, 0xdd, 0xc5, 0x21, 0x77, 0xf0, 0x5e, 0x8c, 0xb9, 0x80, 0x5b,
	0x00, 0x9c, 0xb7, 0xd2, 0x36, 0x56, 0x8c, 0xfe, 0xfc, 0xf0, 0xba, 0xa5, 0x11, 0xd2, 0x5e, 0x2c,
	0x35, 0x23, 0xdd, 0x91, 0x75, 0x1b, 0xf9, 0x58, 0xe7, 0x3a, 0xb9, 0x4c, 0xf3, 0x1b, 0x03, 0x3c,
	0x51, 0x28, 0xcf, 0x23, 0x1a, 0x72, 0x0c, 0xdf, 0x02, 0x0d, 0x21, 0x2d, 0x6d, 0x63, 0xe5, 0x4a,
	0x7f, 0x7e, 0x68, 0x5a, 0x53, 0x63, 0xb6, 0x3e, 0x64, 0x28, 0x8a, 0xb0, 0x77, 0x33, 0x89, 0x64,
	0xf2, 0x46, 0xf3, 0xe8, 0xb8, 0x37, 0xf7, 0xed, 0xdf, 0x3f, 0xac, 0x19, 0x8e, 0x4e, 0x86, 0x6f,
	0x17, 0x68, 0xd6, 0x24, 0xcd, 0xe7, 0x2e, 0xa5, 0xa9, 0x38, 0x14, 0x78, 0x3e, 0x03, 0x16, 0xcf,
	0x69, 0x66, 0x43, 0x68, 0x81, 0x1a, 0xf1, 0x64, 0xf3, 0x4d, 0xa7, 0x46, 0x3c, 0xf3, 0x56, 0x7e,
	0x54, 0x67, 0xad, 0xbc, 0x0a, 0xea, 0x92, 0x8d, 0x9e, 0xd2, 0x0c, 0x9d, 0x38, 0x2a, 0xc1, 0xfc,
	0xb1, 0x06, 0x1e, 0x9f, 0x70, 0x4d, 0x62, 0x42, 0x0b, 0xd4, 0xe9, 0x41, 0x88, 0x99, 0x6c, 0xae,
	0xb9, 0xd1, 0xfe, 0xe5, 0xa7, 0xc1, 0x92, 0xee, 0xef, 0x0d, 0xcf, 0x63, 0x98, 0xf3, 0xbb, 0x82,
	0x91, 0xd0, 0x77, 0x54, 0x18, 0x7c, 0x0d, 0x00, 0x59, 0xdc, 0x4d, 0xb7, 0xa8, 0x7d, 0x65, 0xc5,
	0xe8, 0xb7, 0x86, 0xbd, 0x12, 0x4a, 0x19, 0xe0, 0x76, 0x12, 0x61, 0xa7, 0x29, 0xb2, 0x9f, 0x70,
	0x15, 0xb4, 0x28, 0x23, 0x3e, 0x09, 0xdd, 0x00, 0x91, 0xf1, 0x88, 0x1e, 0xb6, 0x1f, 0x91, 0x5c,
	0x16, 0x94, 0xf5, 0x7d, 0x65, 0x84, 0xd7, 0xc0, 0x63, 0x3a, 0xcc, 0xc3, 0x21, 0x0d, 0xda, 0x75,
	0x19, 0x34, 0xaf, 0x6c, 0x9b, 0xa9, 0x09, 0x7e, 0x00, 0x1a, 0x84, 0x07, 0x2e, 0xf1, 0xda, 0x8f,
	0x4a, 0xea, 0xaf, 0x1f, 0x1d, 0xf7, 0x8c, 0xdf, 0x8f, 0x7b, 0xaf, 0xf8, 0x44, 0xdc, 0x8b, 0x47,
	0xd6, 0x0e, 0x0d, 0x6c, 0xc1, 0x68, 0xb2, 0x8b, 0x39, 0x1f, 0x63, 0x66, 0x9f, 0x71, 0x1c, 0x68,
	0xc9, 0xc4, 0x82, 0x8c, 0xad, 0x9b, 0xf8, 0x50, 0xf7, 0xe9, 0xd4, 0x09, 0x0f, 0xde, 0xf1, 0xcc,
	0xe7, 0xc1, 0xb2, 0x3c, 0x85, 0x0d, 0x46, 0x3c, 0x1f, 0x7b, 0x77, 0xe3, 0x28, 0x1a, 0x27, 0x55,
	0x47, 0x46, 0x40, 0xa7, 0x2c, 0x58, 0x1f, 0xdd, 0xbb, 0xa0, 0x35, 0x52, 0x0e, 0x97, 0x4b, 0x8f,
	0x3e, 0xc3, 0xe5, 0xc2, 0x0a, 0x65, 0xcb, 0xf3, 0x26, 0x25, 0x85, 0x25, 0x5c, 0x18, 0xe5, 0x8b,
	0x9a, 0x5c, 0xf3, 0x72, 0x70, 0x40, 0x05, 0x76, 0x68, 0x2c, 0x30, 0xe3, 0x15, 0xbc, 0x26, 0xf4,
	0x55, 0xfb, 0xcf, 0xfa, 0xfa, 0xde, 0xd0, 0x0d, 0x4e, 0xa0, 0xea, 0x06, 0xb7, 0x40, 0x8b, 0x49,
	0x87, 0xcb, 0x94, 0x47, 0xcb, 0xad, 0x6c, 0x23, 0xf2, 0x15, 0x9c, 0x05, 0x96, 0xaf, 0xf7, 0xff,
	0xe9, 0xec, 0x13, 0xd0, 0x93, 0x74, 0xef, 0xc4, 0x69, 0x75, 0x89, 0xb1, 0xcd, 0x50, 0xc8, 0x3f,
	0xc5, 0xac, 0x6a, 0x54, 0x03, 0x00, 0x3d, 0xcc, 0x85, 0xae, 0xe0, 0x7a, 0x34, 0x40, 0x44, 0x71,
	0x68, 0x3a, 0x8b, 0x39, 0xcf, 0xa6, 0x74, 0x98, 0x5f, 0x19, 0x60, 0xa5, 0x1a, 0x42, 0xcf, 0x65,
	0x0f, 0xcc, 0xfb, 0x88, 0xbb, 0x11, 0x4a, 0x02, 0x1c, 0x0a, 0x3d, 0x94, 0x0b, 0x4e, 0xfd, 0xe5,
	0xf4, 0xd4, 0xbf, 0xfb, 0xa3, 0xd7, 0xcf, 0xed, 0xae, 0xde, 0x52, 0xf5, 0x6f, 0xc0, 0xbd, 0x5d,
	0x7d, 0x71, 0xa7, 0x09, 0x5c, 0x6d, 0x08, 0xf0, 0x11, 0xbf, 0xad, 0x30, 0x86, 0x9f, 0x37, 0x40,
	0x5d, 0xf2, 0x82, 0x31, 0x68, 0xa8, 0xdb, 0x10, 0xae, 0x96, 0x1c, 0xc3, 0xf4, 0x65, 0xdc, 0xb9,
	0x7e, 0x59, 0x98, 0xea, 0xca, 0xbc, 0xfa, 0xd9, 0xaf, 0x7f, 0x7d, 0x59, 0x7b, 0x12, 0x2e, 0x9d,
	0x6b, 0x49, 0xbe, 0x4f, 0x14, 0xd8, 0x01, 0xa8, 0xab, 0x2b, 0xe6, 0xd9, 0x0b, 0xcb, 0x65, 0xa0,
	0xab, 0x97, 0x44, 0x69, 0xcc, 0x6b, 0x12, 0xf3, 0x29, 0xb8, 0x5c, 0x86, 0x69, 0xdf, 0x27, 0xde,
	0x03, 0xf8, 0xb5, 0x01, 0x16, 0x0a, 0xfa, 0x83, 0x2f, 0x54, 0xd5, 0x2e, 0xd3, 0x74, 0x67, 0x30,
	0x63, 0xb4, 0x66, 0xf4, 0xa2, 0x64, 0xb4, 0x06, 0xfb, 0x95, 0x8c, 0xec, 0xa2, 0xe8, 0x25, 0xc1,
	0x82, 0x7e, 0xaa, 0x09, 0x96, 0x89, 0xbb, 0x9a, 0x60, 0xa9, 0x28, 0x67, 0x21, 0x58, 0x14, 0x2d,
	0xfc, 0x59, 0xbe, 0x45, 0xa7, 0xd6, 0x19, 0x0e, 0xab, 0x80, 0xab, 0xe5, 0xd5, 0xb9, 0xf1, 0xaf,
	0x72, 0x34, 0xe5, 0xf7, 0x24, 0xe5, 0x2d, 0xb8, 0x59, 0x4d, 0x79, 0x2f, 0x96, 0x8c, 0x15, 0x71,
	0xa1, 0x0b, 0xd8, 0xf7, 0xa7, 0xa5, 0xfb, 0x60, 0xe3, 0xd6, 0xd1, 0x49, 0xd7, 0x78, 0x78, 0xd2,
	0x35, 0xfe, 0x3c, 0xe9, 0x1a, 0x5f, 0x9c, 0x76, 0xe7, 0x1e, 0x9e, 0x76, 0xe7, 0x7e, 0x3b, 0xed,
	0xce, 0x7d, 0xf4, 0xd2, 0xac, 0xef, 0x86, 0x43, 0xf5, 0xb5, 0x24, 0x15, 0x37, 0x6a, 0xc8, 0x2f,
	0x99, 0x1b, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x5f, 0x19, 0x6d, 0x00, 0xca, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Tokens ...
	Tokens(ctx context.Context, in *QueryTokensRequest, opts ...grpc.CallOption) (*QueryTokensResponse, error)
	// Token ...
	Token(ctx context.Context, in *QueryTokenRequest, opts ...grpc.CallOption) (*QueryTokenResponse, error)
	// BridgedSupply ...
	BridgedSupply(ctx context.Context, in *QueryBridgedSupplyRequest, opts ...grpc.CallOption) (*QueryBridgedSupplyResponse, error)
	// RemoteRouters ...
	RemoteRouters(ctx context.Context, in *QueryRemoteRoutersRequest, opts ...grpc.CallOption) (*QueryRemoteRoutersResponse, error)
	// QuoteRemoteTransfer ...
	QuoteRemoteTransfer(ctx context.Context, in *QueryQuoteRemoteTransferRequest, opts ...grpc.CallOption) (*QueryQuoteRemoteTransferResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Tokens(ctx context.Context, in *QueryTokensRequest, opts ...grpc.CallOption) (*QueryTokensResponse, error) {
	out := new(QueryTokensResponse)
	err := c.cc.Invoke(ctx, "/hyperlane.warp.v1.Query/Tokens", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Token(ctx context.Context, in *QueryTokenRequest, opts ...grpc.CallOption) (*QueryTokenResponse, error) {
	out := new(QueryTokenResponse)
	err := c.cc.Invoke(ctx, "/hyperlane.warp.v1.Query/Token", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BridgedSupply(ctx context.Context, in *QueryBridgedSupplyRequest, opts ...grpc.CallOption) (*QueryBridgedSupplyResponse, error) {
	out := new(QueryBridgedSupplyResponse)
	err := c.cc.Invoke(ctx, "/hyperlane.warp.v1.Query/BridgedSupply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RemoteRouters(ctx context.Context, in *QueryRemoteRoutersRequest, opts ...grpc.CallOption) (*QueryRemoteRoutersResponse, error) {
	out := new(QueryRemoteRoutersResponse)
	err := c.cc.Invoke(ctx, "/hyperlane.warp.v1.Query/RemoteRouters", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) QuoteRemoteTransfer(ctx context.Context, in *QueryQuoteRemoteTransferRequest, opts ...grpc.CallOption) (*QueryQuoteRemoteTransferResponse, error) {
	out := new(QueryQuoteRemoteTransferResponse)
	err := c.cc.Invoke(ctx, "/hyperlane.warp.v1.Query/QuoteRemoteTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Tokens ...
	Tokens(context.Context, *QueryTokensRequest) (*QueryTokensResponse, error)
	// Token ...
	Token(context.Context, *QueryTokenRequest) (*QueryTokenResponse, error)
	// BridgedSupply ...
	BridgedSupply(context.Context, *QueryBridgedSupplyRequest) (*QueryBridgedSupplyResponse, error)
	// RemoteRouters ...
	RemoteRouters(context.Context, *QueryRemoteRoutersRequest) (*QueryRemoteRoutersResponse, error)
	// QuoteRemoteTransfer ...
	QuoteRemoteTransfer(context.Context, *QueryQuoteRemoteTransferRequest) (*QueryQuoteRemoteTransferResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Tokens(ctx context.Context, req *QueryTokensRequest) (*QueryTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tokens not implemented")
}
func (*UnimplementedQueryServer) Token(ctx context.Context, req *QueryTokenRequest) (*QueryTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Token not implemented")
}
func (*UnimplementedQueryServer) BridgedSupply(ctx context.Context, req *QueryBridgedSupplyRequest) (*QueryBridgedSupplyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BridgedSupply not implemented")
}
func (*UnimplementedQueryServer) RemoteRouters(ctx context.Context, req *QueryRemoteRoutersRequest) (*QueryRemoteRoutersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoteRouters not implemented")
}
func (*UnimplementedQueryServer) QuoteRemoteTransfer(ctx context.Context, req *QueryQuoteRemoteTransferRequest) (*QueryQuoteRemoteTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuoteRemoteTransfer not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Tokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Tokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hyperlane.warp.v1.Query/Tokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Tokens(ctx, req.(*QueryTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Token_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Token(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hyperlane.warp.v1.Query/Token",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Token(ctx, req.(*QueryTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BridgedSupply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBridgedSupplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BridgedSupply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hyperlane.warp.v1.Query/BridgedSupply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BridgedSupply(ctx, req.(*QueryBridgedSupplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RemoteRouters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRemoteRoutersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RemoteRouters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hyperlane.warp.v1.Query/RemoteRouters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RemoteRouters(ctx, req.(*QueryRemoteRoutersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_QuoteRemoteTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryQuoteRemoteTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).QuoteRemoteTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hyperlane.warp.v1.Query/QuoteRemoteTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).QuoteRemoteTransfer(ctx, req.(*QueryQuoteRemoteTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hyperlane.warp.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Tokens",
			Handler:    _Query_Tokens_Handler,
		},
		{
			MethodName: "Token",
			Handler:    _Query_Token_Handler,
		},
		{
			MethodName: "BridgedSupply",
			Handler:    _Query_BridgedSupply_Handler,
		},
		{
			MethodName: "RemoteRouters",
			Handler:    _Query_RemoteRouters_Handler,
		},
		{
			MethodName: "QuoteRemoteTransfer",
			Handler:    _Query_QuoteRemoteTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hyperlane/warp/v1/query.proto",
}

func (m *QueryTokensRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokensRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokensRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTokensResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokensResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokensResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Tokens) > 0 {
		for iNdEx := len(m.Tokens) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Tokens[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryTokenRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokenRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokenRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTokenResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTokenResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTokenResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Token != nil {
		{
			size, err := m.Token.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *WrappedHypToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WrappedHypToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WrappedHypToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsmId != nil {
		{
			size := m.IsmId.Size()
			i -= size
			if _, err := m.IsmId.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if len(m.OriginDenom) > 0 {
		i -= len(m.OriginDenom)
		copy(dAtA[i:], m.OriginDenom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OriginDenom)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.OriginMailbox) > 0 {
		i -= len(m.OriginMailbox)
		copy(dAtA[i:], m.OriginMailbox)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OriginMailbox)))
		i--
		dAtA[i] = 0x22
	}
	if m.TokenType != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.TokenType))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBridgedSupplyRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBridgedSupplyRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBridgedSupplyRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBridgedSupplyResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBridgedSupplyResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBridgedSupplyResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BridgedSupply.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRemoteRoutersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRemoteRoutersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRemoteRoutersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryRemoteRoutersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRemoteRoutersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRemoteRoutersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.RemoteRouters) > 0 {
		for iNdEx := len(m.RemoteRouters) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RemoteRouters[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryQuoteRemoteTransferRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryQuoteRemoteTransferRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryQuoteRemoteTransferRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DestinationDomain) > 0 {
		i -= len(m.DestinationDomain)
		copy(dAtA[i:], m.DestinationDomain)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DestinationDomain)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryQuoteRemoteTransferResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryQuoteRemoteTransferResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryQuoteRemoteTransferResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GasPayment) > 0 {
		for iNdEx := len(m.GasPayment) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GasPayment[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryTokensRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTokensResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Tokens) > 0 {
		for _, e := range m.Tokens {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTokenRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTokenResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Token != nil {
		l = m.Token.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *WrappedHypToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.TokenType != 0 {
		n += 1 + sovQuery(uint64(m.TokenType))
	}
	l = len(m.OriginMailbox)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.OriginDenom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.IsmId != nil {
		l = m.IsmId.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBridgedSupplyRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBridgedSupplyResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BridgedSupply.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRemoteRoutersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRemoteRoutersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.RemoteRouters) > 0 {
		for _, e := range m.RemoteRouters {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryQuoteRemoteTransferRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.DestinationDomain)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryQuoteRemoteTransferResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.GasPayment) > 0 {
		for _, e := range m.GasPayment {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryTokensRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokensRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokensRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTokensResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokensResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokensResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tokens = append(m.Tokens, WrappedHypToken{})
			if err := m.Tokens[len(m.Tokens)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTokenRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokenRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokenRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTokenResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTokenResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTokenResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Token", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Token == nil {
				m.Token = &WrappedHypToken{}
			}
			if err := m.Token.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WrappedHypToken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WrappedHypToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WrappedHypToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenType", wireType)
			}
			m.TokenType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TokenType |= HypTokenType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginMailbox", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginMailbox = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsmId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_troykessler_hyperlane_cosmos_util.HexAddress
			m.IsmId = &v
			if err := m.IsmId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBridgedSupplyRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBridgedSupplyRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBridgedSupplyRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBridgedSupplyResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBridgedSupplyResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBridgedSupplyResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgedSupply", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BridgedSupply.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRemoteRoutersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRemoteRoutersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRemoteRoutersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRemoteRoutersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRemoteRoutersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRemoteRoutersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemoteRouters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RemoteRouters = append(m.RemoteRouters, &RemoteRouter{})
			if err := m.RemoteRouters[len(m.RemoteRouters)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryQuoteRemoteTransferRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryQuoteRemoteTransferRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryQuoteRemoteTransferRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationDomain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationDomain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryQuoteRemoteTransferResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryQuoteRemoteTransferResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryQuoteRemoteTransferResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasPayment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GasPayment = append(m.GasPayment, types.Coin{})
			if err := m.GasPayment[len(m.GasPayment)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
